/**
 * Shared facility suggestions for Destinations → project facilities.
 * Sourced from Hacienda West, GAIA, Fouka Bay, and D-Bay public amenity lists.
 */
export const FACILITY_SUGGESTIONS = [
  'Private sandy beach',
  'Private Mediterranean beach',
  'Crystal Lagoons',
  'Crystal lagoon',
  'Swimmable lagoons & water features',
  'Internal lagoons',
  'Beach club / Beach hub',
  'Clubhouse',
  'Clubhouses',
  'Beach clubhouse',
  'Community hub',
  'Swimming pools',
  'Multiple swimming pools',
  'Signature swimming pool',
  'Outdoor pools',
  'Kids pool / water park',
  'Covered / ladies pool',
  'Aqua park / water activities',
  'Gym / Health club',
  'Fully equipped gym',
  'Outdoor gym',
  'Spa & wellness',
  'Spa / health club',
  'Health club (gym, spa, sauna, jacuzzi)',
  'Sports arena (tennis / padel)',
  'Sports courts (tennis / multi-purpose)',
  'Sports facilities & courts',
  'Gym / sports zone',
  'Jogging & cycling tracks',
  'Walking & cycling tracks',
  'Walking, jogging & cycling tracks',
  'Commercial strip / retail',
  'Commercial strip',
  'Commercial hub (shops / F&B)',
  'Commercial mall / retail',
  'Restaurants & cafes',
  'Fine dining (beachside restaurants)',
  'Promenade restaurants & cafes',
  'Kids play area',
  'Kids entertainment area',
  'Kids area',
  'Hotel / hospitality',
  'Branded hotel',
  'KYND hotel / hospitality',
  'Business hub',
  'Medical clinic / pharmacy',
  'Medical center / pharmacy',
  'Medical center & pharmacy',
  'Pharmacy / medical clinic',
  '24/7 security & CCTV',
  '24/7 security',
  'Gated entry',
  'Landscaped gardens',
  'Maintenance services',
  'Golf carts',
  'Diving center',
  'Water sports / kayaking',
  'Yoga / meditation areas',
  'Barbecue area',
  'Guest parking',
  'Underground parking',
  'Hypermarket / grocery',
  'Cultural center',
  'Nightlife / lounges',
  'Concierge / customer care',
  'Housekeeping services',
];
